
# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 18:16
from __future__ import unicode_literals

import django
import fernet_fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0018_azure_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='AzureCredentials',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='AzureCredentials',
            name='azure_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='AzureCredentials',
            name='client_id',
        ),
        migrations.AddField(
            model_name='AzureCredentials',
            name='azure_client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='AzureCredentials',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='AzureCredentials',
            name='azure_secret',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='AzureCredentials',
            name='tenant',
        ),
        migrations.AddField(
            model_name='AzureCredentials',
            name='azure_tenant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]