
# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 18:16
from __future__ import unicode_literals

import django
import fernet_fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0019_azure_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='AZURE',
            name='default_user_name',
        ),
        migrations.AddField(
            model_name='AZURE',
            name='vm_default_user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]